# Generated by Django 5.0.3 on 2024-04-12 18:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('image', models.ImageField(blank=True, upload_to='cafeteria_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('student_limit', models.IntegerField(default=0)),
                ('current_no_students', models.IntegerField(default=0, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('visible', models.BooleanField(default=False, null=True)),
                ('amount_tobe_paid', models.IntegerField(default=0, null=True)),
                ('rebate_rate', models.IntegerField(default=160, null=True)),
                ('image', models.ImageField(blank=True, upload_to='caterer_images/')),
            ],
            options={
                'verbose_name': 'Caterer',
                'verbose_name_plural': 'Caterers',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('pos', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='messPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Mess Period',
                'verbose_name_plural': 'Mess Periods',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('rule_text', models.TextField(default='')),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='shortRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_applied', models.DateField(default=datetime.date.today)),
                ('amount', models.IntegerField(null=True)),
                ('mess_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.messperiod')),
                ('rebating_caterer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caterer', to='home.caterer')),
            ],
            options={
                'verbose_name': 'Short Rebate Details',
                'verbose_name_plural': 'Short Rebate Details',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('caterer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer')),
                ('mess_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.messperiod')),
                ('short_rebates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_short_rebates', to='home.shortrebate')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('roll_no', models.CharField(blank=True, default='', max_length=20)),
                ('rebate_amount', models.IntegerField(default=0, null=True)),
                ('total_fees', models.IntegerField(default=16000, null=True)),
                ('shortrebate_days', models.IntegerField(default=0, null=True)),
                ('caterer_alloted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer')),
            ],
            options={
                'verbose_name': 'Student Details',
                'verbose_name_plural': 'Student Details',
            },
        ),
        migrations.AddField(
            model_name='shortrebate',
            name='student_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student', verbose_name='Student Email'),
        ),
        migrations.CreateModel(
            name='longRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField(default=8)),
                ('approved', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, choices=[('', 'Choose the reason'), ('Incomplete form', 'Incomplete form'), ('There is a date mismatch between the one written in the form and the one in the attached form', 'There is a date mismatch between the one written in the form and the one in the attached form')], default='')),
                ('date_applied', models.DateField(default=datetime.date.today)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='documents/')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student')),
            ],
            options={
                'verbose_name': 'Long Rebate Details',
                'verbose_name_plural': 'Long Rebate Details',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('jain', models.BooleanField(blank=True, default=False, null=True)),
                ('caterer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer')),
                ('period', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.period')),
                ('email', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student')),
            ],
            options={
                'verbose_name': 'Allocation Detail',
                'verbose_name_plural': 'Allocation Details',
            },
        ),
    ]
