# Generated by Django 5.0.3 on 2024-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alloted_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
