# Generated by Django 5.0.3 on 2024-04-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_semester_student_longrebate_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mess_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.messperiod'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.semester'),
        ),
    ]
