# Generated by Django 5.0.3 on 2024-04-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shortrebate_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='messperiod',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.semester'),
        ),
    ]
