# Generated by Django 5.0.3 on 2024-04-16 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_semester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='longrebate',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.semester'),
        ),
    ]
