# Generated by Django 5.0.3 on 2024-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_longrebate_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortrebate',
            name='days_applied',
            field=models.IntegerField(default=2),
        ),
    ]
