# Generated by Django 5.0.3 on 2024-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_shortrebate_days_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='messperiod',
            name='allotment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/cafeteria_images/'),
        ),
        migrations.AlterField(
            model_name='caterer',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/caterer_images/'),
        ),
        migrations.AlterField(
            model_name='longrebate',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/documents/'),
        ),
    ]
