# Generated by Django 5.0.3 on 2024-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_allotment_done_messperiod_allotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='image',
            field=models.ImageField(blank=True, upload_to='cafeteria_images/'),
        ),
        migrations.AlterField(
            model_name='caterer',
            name='image',
            field=models.ImageField(blank=True, upload_to='caterer_images/'),
        ),
        migrations.AlterField(
            model_name='longrebate',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/'),
        ),
    ]
